export { TranslateStore } from './translate.store';
export { provideTranslate } from './provide-translate';
export { TranslatePipe } from './translate.pipe';
export { injectTranslate } from './translate-fn';
export type { TranslateFn } from './translate-fn';
export { mark } from './mark';
export type { MarkOptions } from './mark';
export { TranslateDirective, TranslateSlot } from './translate.directive';
export { TranslateSlotOutlet } from './translate-slot-outlet.directive';
export type { TranslateSlotContext } from './translate.directive';
export { MESSAGE_FORMATTER } from './message-formatter';
export type { MessageFormatter } from './message-formatter';
export { parseSlots, slotsToText } from './slot-parser';
export type { SlotNode } from './slot-parser';
export type { TranslateConfig, TranslateOptions, TranslationLoader, Translations } from './types';
